### ISSUE TITLE
Add a spec for socket/socket_server

### ISSUE THREAD

**Issue by LuxMiranda** [SmallSatGasTeam/OpenSPA#13]
Particularly testing the listen method

**Comment by nick-benoit14** [comment]
So this might not be a great first task after looking into it a little more. This might not be a 'Do this thing' sort of task as much of a, 'figure out how to test' something like the socket and server socket. We definitely will want tests for these things in the future, but i'm not quite sure how to test them right now. It is hard to test things that have system calls like that.

**Comment by nick-benoit14** [comment]
Choosing another issue might be an easier introduction however
