### ISSUE TITLE
Replace 'test/mocks/local_communicator' with 'test/mocks/physical_communicator.hpp'

### ISSUE THREAD

**Issue by LuxMiranda** [SmallSatGasTeam/OpenSPA#15]

**Comment by nick-benoit14** [comment]
So basically there is a mock class called `MockLocalCommunicator` that gets used in some tests. That should probably instead be a `MockPhysicalCommunicator`. 
To make this change: 
 * Create MockPhysicalCommunicator using google mock 
 * Replace all instances of MockLocalCommunicator with your new MockPhysicalCommunicator
