### ISSUE TITLE
Develop subscription service

### ISSUE THREAD

**Issue by LuxMiranda** [SmallSatGasTeam/OpenSPA#35]
Weehaa!

**Comment by nick-benoit14** [comment]
I was thinking I would just do my brainstorming, and thinking through this here so that there is a more public record of it. So below will be thoughts, and ideas about how this could work.

**Comment by nick-benoit14** [comment]
It seems like the sub tasks for this are: 
* ~~Add subscription message~~
* ~~Add subscription reply~~
* Add subscription message handling to component class 
    * Add subscriptions record keeping 
        * I can't think of any good reason for this not to just be a vector of subscriptions. (Or maybe there is, this does not do a great job of supporting the priority feature)
    * Keep track of data being produced by a componnet
        * What should this API look like? 
    * Send out data on applicable schedule 
        * What does doing something on an interval look like in c++?
        * Maybe we could have a priority queue of subscriptions, they get popped of the queue and handled. Is this a better way to support priority?

**Comment by LuxMiranda** [comment]
More out-loud brainstorming
- ~We need to determine whether we want to implement the lookup service now or just let components subscribe directly to each other for the moment~ We'll put off the lookup service.
- ~~I think we can just send SpaData messages between the components that are subscribed to each other~~ SpaData implemented!  
- ~~I was also thinking a priority queue for subscriptions, but I'm unsure if we ought to use a std::priority_queue or just pretend that a vector is a priority queue. This may be something we have to test on the hardware?~~ Resolved, see below

**Comment by nick-benoit14** [comment]
I think probably a vector
I don't think that a priority queue would quite do what we need it to. We would need to build custom logic so that we still would service subscriptions that aren't the highest priority.

**Comment by LuxMiranda** [comment]
Resolution: We shall not implement the priority feature this time around!

**Comment by LuxMiranda** [comment]
I think that when a component receives SpaData, it should handle that on a per-component basis. For example, if it's just a radio pumping out the data, say, it only needs to handle the current iteration of data from the aggregator each time that it receives it. A median filter, on the other hand, will need to keep track of a buffer of _n_ data-points.

**Comment by nick-benoit14** [comment]
I'm not quite sure I am following you. Have we proposed any other thought, other than each component being able to handle spa messages their own way?
