### ISSUE TITLE
Write a SPA wrapper for the barometer

### ISSUE THREAD

**Issue by LuxMiranda** [SmallSatGasTeam/OpenSPA#41]
This assignment will involve working with physical hardware in the GAS laboratory.

We are finally at the point in which we can start writing SPA wrappers for our physical sensors! A SPA wrapper is basically a class that takes the drivers for a given sensor and arranges its functionality into something that is SPA-compliant. Essentially, it should arrange the sensor's output into SpaData messages, handle incoming messages in a meaningful way, and handle other sensor-specific logic.

The SPA wrapper should be in `lib/components` and inherit from `Component`

This, of course, requires interfacing the sensor with the Beaglebone Black. Study our [previous payload code](https://github.com/SmallSatGasTeam/errno_3) to find the necessary libraries and see how to use each sensor!

**Comment by nick-benoit14** [comment]
So my thought was to have a single spa component that wraps all of the sensors? Any thoughts?

**Comment by LuxMiranda** [comment]
Hmm... That would have the advantage of not really needing to write an aggregator. That might involve some weird logic,  though,  since the boom relies on barometer readings and since we want to use a median filter for those. 

My thought was we could just write an individual wrapper for each sensor to take advantage of the spa network for the sensors that need to communicate. This also has the benefit of us being able to maintain them and release them as part of a library SPA wrappers for certain devices once we have a full-fledged OpenSPA release.

**Comment by nick-benoit14** [comment]
I think writing a component for each sensor would be a lot of unnecessary over head, both in workload for us and maybe even on the SpaNetwork. I was thinking we could basically have 

* Data component
* Filtering and cleanup component
* Logging / Radio component
* Boom component

**Comment by nick-benoit14** [comment]
Thoughts?

**Comment by LuxMiranda** [comment]
Hmm... You do have a point about the overhead on th network. This would also simplify things a bit! 

Let's go with that instead. We can alway separate out things into individual wrappers later if we decide to.

**Comment by nick-benoit14** [comment]
I think writing the data component in a modular way is a good idea, I just dont think that each sensor being its own component is the best way to accomplish this decoupling.

**Comment by LuxMiranda** [comment]
Right, I see your case now. Well, awesome! I'll update the issues
appropriately. I'm excited!
